/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Exam = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'progress' : IDL.Nat,
  'examType' : IDL.Text,
  'dateTime' : IDL.Int,
  'location' : IDL.Text,
});
export const Folder = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'pinned' : IDL.Bool,
  'folderId' : IDL.Text,
  'favorite' : IDL.Bool,
});
export const Topic = IDL.Record({
  'id' : IDL.Text,
  'references' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
});
export const Chapter = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'topics' : IDL.Vec(Topic),
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createExam' : IDL.Func([Exam], [], []),
  'createFolder' : IDL.Func([Folder], [], []),
  'createNote' : IDL.Func([Note], [], []),
  'createSubject' : IDL.Func([Subject], [], []),
  'deleteExam' : IDL.Func([IDL.Text], [], []),
  'deleteFolder' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'getExamsBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
  'getFavoriteNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getPinnedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getUpcomingExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'searchSyllabus' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'updateExam' : IDL.Func([Exam], [], []),
  'updateFolder' : IDL.Func([Folder], [], []),
  'updateNote' : IDL.Func([Note], [], []),
  'updateSubject' : IDL.Func([Subject], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Exam = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'progress' : IDL.Nat,
    'examType' : IDL.Text,
    'dateTime' : IDL.Int,
    'location' : IDL.Text,
  });
  const Folder = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'pinned' : IDL.Bool,
    'folderId' : IDL.Text,
    'favorite' : IDL.Bool,
  });
  const Topic = IDL.Record({
    'id' : IDL.Text,
    'references' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Chapter = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'topics' : IDL.Vec(Topic),
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createExam' : IDL.Func([Exam], [], []),
    'createFolder' : IDL.Func([Folder], [], []),
    'createNote' : IDL.Func([Note], [], []),
    'createSubject' : IDL.Func([Subject], [], []),
    'deleteExam' : IDL.Func([IDL.Text], [], []),
    'deleteFolder' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'getExamsBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
    'getFavoriteNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getPinnedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getUpcomingExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'searchSyllabus' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'updateExam' : IDL.Func([Exam], [], []),
    'updateFolder' : IDL.Func([Folder], [], []),
    'updateNote' : IDL.Func([Note], [], []),
    'updateSubject' : IDL.Func([Subject], [], []),
  });
};

export const init = ({ IDL }) => { return []; };