/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : string,
  'name' : string,
  'topics' : Array<Topic>,
}
export interface Exam {
  'id' : string,
  'title' : string,
  'subject' : string,
  'completed' : boolean,
  'progress' : bigint,
  'examType' : string,
  'dateTime' : bigint,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface Folder {
  'id' : string,
  'name' : string,
  'parentId' : [] | [string],
}
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'blob' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'tags' : Array<string>,
  'pinned' : boolean,
  'folderId' : string,
  'favorite' : boolean,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'chapters' : Array<Chapter>,
}
export interface Topic {
  'id' : string,
  'references' : Array<string>,
  'order' : bigint,
  'name' : string,
  'completed' : boolean,
  'notes' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createExam' : ActorMethod<[Exam], undefined>,
  'createFolder' : ActorMethod<[Folder], undefined>,
  'createNote' : ActorMethod<[Note], undefined>,
  'createSubject' : ActorMethod<[Subject], undefined>,
  'deleteExam' : ActorMethod<[string], undefined>,
  'deleteFolder' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'getExamsBySubject' : ActorMethod<[string], Array<Exam>>,
  'getFavoriteNotes' : ActorMethod<[], Array<Note>>,
  'getPinnedNotes' : ActorMethod<[], Array<Note>>,
  'getUpcomingExams' : ActorMethod<[], Array<Exam>>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'searchSyllabus' : ActorMethod<[string], Array<string>>,
  'updateExam' : ActorMethod<[Exam], undefined>,
  'updateFolder' : ActorMethod<[Folder], undefined>,
  'updateNote' : ActorMethod<[Note], undefined>,
  'updateSubject' : ActorMethod<[Subject], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];